### ISSUE TITLE
Add git to image

### ISSUE THREAD

**Issue by mdeweerd** [phan/docker#7]
'git' would be a useful addition `apk add git` fails more often than non in the github ci flow.

Without git, the checkout actually downloads an archive that does not include the .github directory.

```yaml
---
on: [pull_request, push]
name: phan
jobs:
  phan:
    name: Run phan
    runs-on: ubuntu-latest
    container:
      image: phanphp/phan:latest
    steps:
      - name: Link paths and add git
        shell: sh
        run: |
          ln -s $GITHUB_WORKSPACE /mnt/src
          apk add git

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Phan
        run: |
          cd /mnt/src
          set -o pipefail
          /opt/phan/phan -k /mnt/src/.github/workflows/phan_config.php -B /mnt/src/.github/workflows/phan_baseline.txt --analyze-twice --minimum-target-php-version 5.6
```
